"""Update UserBase

Revision ID: 663d0c7d3748
Revises: f5dc9d7cc1ab
Create Date: 2023-07-18 15:28:11.492896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663d0c7d3748'
down_revision = 'f5dc9d7cc1ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
