"""Change type

Revision ID: b2895328a945
Revises: 4a3d28593ef8
Create Date: 2023-08-17 12:37:07.671724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2895328a945'
down_revision = '4a3d28593ef8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answers_answer_id', table_name='answers')
    op.create_index(op.f('ix_answers_answer_id'), 'answers', ['answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_answer_id'), table_name='answers')
    op.create_index('ix_answers_answer_id', 'answers', ['answer_id'], unique=False)
    # ### end Alembic commands ###
